name: your_project_name
description: A new Flutter project.

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/HomeCard.png
    - assets/imag1.png
    - assets/imag2.png
    - assets/imag3.png
    - assets/imag4.png
    - assets/imag5.png
    - assets/imag6.png
    - assets/imag7.png
